### ISSUE TITLE
Update text/images on About page and site footers

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#21]
Need to add/revise text on the About page and site footers to recognize the shift from UnWeb to Mist.io and Sam's upcoming contributions. Also need to remind Steve how to find/edit text on other pages (including "Updates," "Resources" and "Featured Content"). We should also get a Mist.io logo to replace UnWeb's on the About page and an image for Sam.

**Comment by Ironman28** [comment]
Done. Closing. If Mist.io would like an image and description, we can add later!

**Comment by ahelme** [comment]
Great!
