### ISSUE TITLE
Nicer tag cloud (relates to #7)

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#23]
In addition to being non-functional (per ticket #7), our current tag-cloud is ugly and outdated. At least it needs to work, but could we also make it look nicer (or replace it with something else that serves the purpose of inviting users to explore site contents)?

**Comment by Ironman28** [comment]
This is LOW priority compared with making the tag cloud basically functional (per #7)

**Comment by ahelme** [comment]
Steve, can you post examples of what you would like to see?

**Comment by Ironman28** [comment]
You're right. It's fine. Closing!
