### ISSUE TITLE
Comma separated tags merging into one big tag

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#25]
Sometimes - not always - it seems that correctly entered keyword tags, separated by commas, do not resolve as individual keyword tags, but instead merge into one, single, impossibly long tag. An example is here: http://www.criticalcommons.org/Members/AdrianFohr/clips/correlation-causation-and-homers-promotion I don't know if this is related to the system we used to have, which required each tag to be entered on a new line. Even though we now claim to support comma-separated tags, the UI instructions on the Edit --> categorization page still admonishes users to enter (or edit) tags "one-per-line" as seen here: http://www.criticalcommons.org/Members/AdrianFohr/clips/correlation-causation-and-homers-promotion/atct_edit?fieldset=categorization

**Comment by ahelme** [comment]
Hmm, how strange! 

Could it be that
1. the publish form DOES allow comma-separated tags
2. the edit form DOES NOT allow comma-separated tags, and the user has added their tags AFTER publishing?

If so, Markos - is it possible to change the edit form to allow comma-separated tags as per the publish form?

**Comment by Ironman28** [comment]
Not necessary. Closing.
