### ISSUE TITLE
commentaries optimizations - prevent spam HTML in commentaries

### ISSUE THREAD

**Issue by mgogoulos** [plumi/criticalcommons.content#27]
make sure commentaries are stored stripped, all text is saved without html tags, and advancedusers can only add them

**Comment by Ironman28** [comment]
This ticket was created to prevent spam from taking over a page via HTML in commentaries. However, it is necessary for Basic users (not just Advanced) to be able to leave text commentaries on a pre-existing clip. Basic users are automatically approved by the system. Will this be a problem if they continue to be allowed to add commentaries?

**Comment by ahelme** [comment]
It sounds fine to me to allow both Basic and Advanced Users to add commentaries (Markos please suggest any reason otherwise).

**Comment by mgogoulos** [comment]
Sure, makes sense that Basic users can add commentaries, let's keep things single. I'll make sure no html can be added on the commentaries, just text.

**Comment by mgogoulos** [comment]
Also created a new page, http://www.criticalcommons.org/commentaries-review/
Only admins can see it and only if they are logged in (on the header menu, top right) it appears. Every now and then it is advised that you have a look, so you can see what is being added. For example I just saw there are some spam commentaries by user http://www.criticalcommons.org/author/rdelmorotommy (I'll delete them)

**Comment by mgogoulos** [comment]
closing this, Steve please make sure you visit http://www.criticalcommons.org/commentaries-review/ every now and then, and if you notice something strange re-open  this ticket

**Comment by ahelme** [comment]
Looks good Markos!

Steve, just checking you saw this one, with link above.

**Comment by ahelme** [comment]
Markos - I wonder if rich text is possible, as per ticket #10 - thus allowing paragraph breaks?

**Comment by Ironman28** [comment]
Yes, this all looks good. It would be nice to have paragraph breaks in text commentaries if possible! It's weird to have longer commentaries run together into one huge paragraph.
