### ISSUE TITLE
Transcoded file disappeared; manual re-transcode failed

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#28]
When originally uploaded, this clip transcoded and played fine. Now it has disappeared:
http://www.criticalcommons.org/Members/kfortmueller/clips/lady-windermeres-fan-1925-judgmental-glances-at/
I did a manual re-transcode and the systems says 100% for all formats, but I still see no thumbnail or transcoded video to play. I don't know if this is an isolated problem or a symptom of more like this.

**Comment by Ironman28** [comment]
I don't know if this is relevant, but this same clip was later published by a different contributor, which may have had the same file name. Could duplicate file names cause a clip to disappear?
http://www.criticalcommons.org/Members/liserna/clips/look-at-her

**Comment by ahelme** [comment]
That initially sounded plausible, Steve, due to the way videos are stored in folders, within the Member folder. BUT - AFAIK videos are stored within Membername/videoclip so they should not be in conflict if added by different Members....

Markos - do you have any clues on this?

**Comment by Ironman28** [comment]
I just did a manual re-transcode on this video and it worked! Perhaps this problem was related to the Plone update a few weeks ago, which also broke some transcoding functions?

**Comment by Ironman28** [comment]
Not necessary. Closing.
