### ISSUE TITLE
Generate e-mail message to user when an Advanced User account is created

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#3]
When a user registers for Advanced User status, it should generate an e-mail to the user that says the application is pending approval (in addition to the e-mail message that is sent to Steve for approval).

**Comment by ahelme** [comment]
A note related to this, I noticed that notifications are turned OFF when a user submits a video:
http://www.criticalcommons.org/@@plumi-controlpanel > Plumi settings

Could this have happened when the site moved to the new server?

**Comment by Ironman28** [comment]
We have _never_ had notifications for video submissions, but that is a good idea! Could we turn it on? Was there a reason to have it off? Ideally, of course, it would happen only when a clip had been uploaded AND a commentary had been added. Maybe that's the reason?

**Comment by mgogoulos** [comment]
I've enabled the notifications, added a media file and received the email

```
Hi simplemarkos2
Your contribution has been submitted for review before publishing on the site
Title: adsads
```

Would you like this to be changed? I believe there should be a mention to add a commentary so that the video becomes public

Steve, I can generate the email for the advanced user, what should it be?

**Comment by Ironman28** [comment]
Yes, I would like to re-write this message because the video is not really supposed to be reviewed before it is published. It just needs to have a commentary attached.

**Comment by Ironman28** [comment]
Here is the text for the e-mail to be sent when an item is submitted: 

Thank you for sharing media with Critical Commons! 

In order for your submission to be published, it must be accompanied by a critical commentary. For advice on commentaries, please visit: 
http://www.criticalcommons.org/how-to

Add a commentary to:
Samsung Gear VR head mounted display on Stephen Colbert
http://www.criticalcommons.org/Members/ccManager/clips/samsung-gear-vr-head-mounted-dsiplay-on-stephen/view 

Contributor: Critical Commons Manager
Email: plumi.usc@gmail.com

**Comment by mgogoulos** [comment]
Ok, I also need the text for the advanced users email!

**Comment by Ironman28** [comment]
Here you go! Sender should be: plumi.usc@gmail.com

[Subject] Critical Commons Advanced User application 

Dear [XXXX]

Thank you for applying for Advanced User status in Critical Commons! 

We will review your application and respond as quickly as possible -- usually between 5 minutes and 24 hours. If you have any questions, please reply to this message. 
- Critical Commons

**Comment by mgogoulos** [comment]
Should be ok, please check and close ticket if so

**Comment by Ironman28** [comment]
Beautiful!

**Comment by ahelme** [comment]
Cool :)
