### ISSUE TITLE
Ability to export contents of Critical Commons to new platform?

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#30]
One day in the future, we may need to migrate Critical Commons to a new hosting environment that is not Plumi. Is there anything we can or should do now to make this easier when that time comes? 

On a related note, in the event of a crisis -- for example, if Critical Commons' IT admins take us offline due to a security breach -- would there be any way to export the contents of the database in some format that could at least be made available to the individuals who uploaded them? I'm not sure what this would look like, but the lack of control that I feel over our new hosting environment makes me very nervous; at the same time more people are more reliant on Critical Commons than ever. Any ideas?

**Comment by ahelme** [comment]
I assume this is beyond the capacity of the current sprint...

But - Steve, I would say that the easiest thing to do would be to re-create the site from backups, even in a private server environment somewhere if you could not expose it to the internet, and then run some kind of script to export data in a format you might want...

BUT that's just a vague thought from me. Will let Markos say what he thinks best.

ALSO what is your backup strategy for the site? I assume you figured this out with Mist.io and Jeremy?

**Comment by Ironman28** [comment]
We are solid on backups now. Daily snapshots of the entire site and all media. Assuming we can export content in the event of a migration, this ticket can be closed without any action.

**Comment by Ironman28** [comment]
Not necessary. Closing.

**Comment by ahelme** [comment]
Just a note Steve - I guess you'd have to get some developers to address this in the event of such an emergency, and adapt/write you a custom script to export data from Plone. I'm not able to advise what formats you could export into, and how that might be made accessible to a user... for example, how would a user get access to, or understand, a massive database dump from Plone... most easily via re-setting up a Plone site and re-importing the data, I'd imagine! A Plone developer could no doubt advise on this far better than me.

Here's some documentation that might help if this did occur, including an export script that may or may not be useful: http://docs.plone.org/develop/plone/content/importexport.html

If you have funds in the future, you could perhaps look at developing a strategy for dealing with this kind of event OR you could just wait and see if it ever happened, and find some funds and/or sympathetic programmers to deal with it then (which I guess is the option you're choosing, and seems fair to me!).

Great to know about backups!!! I'm assuming there is a documented restore process somewhere...?
