### ISSUE TITLE
Newly added media does not appear on Browse page

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#32]
The browse media (Latest Clips) page http://www.criticalcommons.org/latestclips is supposed to display the most recently added media. However, this page no longer seems to update automatically with newly added clips or images. This is a very recent problem that began only 1-2 weeks ago - perhaps related to the latest Plone patch/update? 

This image was added this morning: http://www.criticalcommons.org/Members/ccManager/clips/business-week-ad-for-vacuum-tubes

**Comment by mgogoulos** [comment]
The issue appeared 7 days ago, after last reboot of the server, where the server got a date of April 2015 strangely! I've set the correct date now and also to check after reboot that the date is set correctly. 

So media that has been added for the last 7 days got a date of April 2015 and thus would not appear on the first page of browse media.

**Comment by ahelme** [comment]
Ahhhh! Strange situation! Cool it's fixed :)

**Comment by ahelme** [comment]
(I tested it :) )
