### ISSUE TITLE
Disable a user's ability to change their status from Basic to Advanced on their account page

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#4]
User's are confused by the drop-down menu that shows their Basic/Advanced status; they think they can change their status themselves, but actually this does nothing. If we can't disable this menu, then perhaps we could make this a way for users to request to change from Basic to Advanced status? Currently there is no way to request a change of status from Basic to Advanced (except for sending Steve a message via the Contact form). This comes up often and is a source of confusion for users.

**Comment by mgogoulos** [comment]
this seems related: http://stackoverflow.com/questions/6174506/hide-custom-fields-on-personal-information-view

**Comment by mgogoulos** [comment]
done, Anna can you test it and if ok close the ticket?

**Comment by mgogoulos** [comment]
To test either visit http://criticalcommons.org/@@personal-information or check the top right button and select my account

**Comment by mgogoulos** [comment]
Are we ok with this for now?

**Comment by Ironman28** [comment]
Fantastic! Closing.

**Comment by ahelme** [comment]
Sorry Markos, couldn't check in on this again until now. Looks solved!
