### ISSUE TITLE
Please add FAQ link to main header navigation bar

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#40]
Sorry for this late addition! 

Please add a link to the FAQ page to the main header:
http://www.criticalcommons.org/FAQ

Link order should now be: 
Home -- Browse -- How to -- [Upload] -- Lectures -- About -- FAQ -- Contact 

I think it's all right to leave the FAQ link in the footer bar also.

**Comment by mgogoulos** [comment]
should be ok now
