### ISSUE TITLE
Please change text of e-mail to uploader! 

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#41]
This ticket replaces #3. It is important to change this text soon, because right now the system is generating messages to users saying that their uploads will be reviewed before they can be published! (We are not allowed to do this under the DMCA!)

Here is the text for the e-mail to be sent when an item is submitted:

Thank you for sharing media with Critical Commons!

In order for your submission to be published, it must be accompanied by a critical commentary. For advice on commentaries, please visit:
http://www.criticalcommons.org/how-to

Add a commentary to:
Samsung Gear VR head mounted display on Stephen Colbert
http://www.criticalcommons.org/Members/ccManager/clips/samsung-gear-vr-head-mounted-dsiplay-on-stephen/view

Contributor: Critical Commons Manager
Email: plumi.usc@gmail.com

**Comment by mgogoulos** [comment]
done, the subject of the email can be improved as well, please submit a media so you will see how the email arrives

**Comment by Ironman28** [comment]
It worked! Here is the e-mail I received:

From: plumi.usc@gmail.com
Subject: Your contribution : Database identity in the creation of Max Headroom : was submitted for review.
Date: October 16, 2015 1:27:23 PM PDT
To: plumi.usc@gmail.com

Thank you for sharing media with Critical Commons!

In order for your submission to be published, it must be accompanied by a critical commentary. For advice on commentaries, please visit:
http://www.criticalcommons.org/how-to

Add a commentary to:
Database identity in the creation of Max Headroom
http://www.criticalcommons.org/Members/ccManager/clips/database-identity-in-the-creation-of-max-headroom

Contributor:Critical Commons Manager
Email:plumi.usc@gmail.com

+++++++++++

The biggest change is to revise the Subject line to be like this: 

"Subject: Your contribution : Database identity in the creation of Max Headroom is awaiting a commentary" 

Please also insert spaces after: 
"Email:" 
"Contributor:"
And remove the extra spaces after "contribution" and before "was submitted" in the Subject line:
"Subject: Your contribution : Database identity in the creation of Max Headroom : "

**Comment by mgogoulos** [comment]
try now, should be ok
