### ISSUE TITLE
Update Terms of Service on Registration page

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#42]
The Terms of Service that appear in a grey box at the bottom of the Registration page during registration do not seem to be updated automatically from the TOS page: 
http://www.criticalcommons.org/TOS

Could we update this box to match the current TOS? This relates to other Registration page issues in #9
![screen shot 2015-10-16 at 12 49 08 pm](https://cloud.githubusercontent.com/assets/5613298/10552131/86b6c866-7406-11e5-8805-e46070af2e66.png)

**Comment by mgogoulos** [comment]
this should be ok now. The text is not updated automatically however, so changes on the /TOS page should be reflected here as well
