### ISSUE TITLE
Minor UI text edits on Registration page

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#43]
This relates to #9, which is closed: 

Now, the Home Page text says "The URL for your external home page, if you have one." 
http://www.criticalcommons.org/register
This is confusing, because this field is now _required_ and returns an error if not completed. Please change this text to say: 
"The URL for an institutional page to verify your affiliation (will not be displayed publicly)." 

For Title, please change to:
"E.g., Professor of Media Studies; Economics Instructor, Graduate Student, Fan Vidder, etc."

For Biography, please change to:
"A short overview of who you are and what you do."  (Delete: "Will be displayed on your author page, linked from the items you create.")

Note: there is currently no way for ordinary users to view any of this information on another user's account page, which is fine.

**Comment by mgogoulos** [comment]
Ok I've changed all above fields. 
We can show some data on the author page, example  http://www.criticalcommons.org/author/ccManager
We can choose to show the above fields only if the user is logged in for example

**Comment by Ironman28** [comment]
This is great! Closing.
