### ISSUE TITLE
Create troubleshooting list for USC IT admin in case of crash

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#44]
Last time the software went down at (2:00AM Athens-time!), our IT admin tried doing a hard-restart of the server, which did not work. Markos inserted code to automate the restart as much as possible (which seems like the best possible solution) and also offered to create a list of things for our USC tech staff to check or do in case this happens again. I would rank this as the highest priority among our remaining tickets!

**Comment by mgogoulos** [comment]
https://github.com/plumi/criticalcommons.content/wiki/Troubleshooting
should be fine for emergencies!

**Comment by Ironman28** [comment]
Thanks, Markos! Closing.
