### ISSUE TITLE
Unable to delete user accounts

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#45]
This relates to (and is an example of) #16 
I am currently not able to delete a user account: 
http://www.criticalcommons.org/@@usergroup-userprefs 
For example, try to delete spam-user accounts in the name of: "Everette" or "Caroline" or "Winifred"
First of all, the attempt takes several minutes, only to return the following error: 

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 1763705289
Varnish cache server

In the past, I got the error message but the command was completed successfully. Now I get the error message, but the account has NOT been deleted. If you try this, you will see what I mean! I think it is important for me to be able to delete user accounts!

**Comment by mgogoulos** [comment]
Confirm this, however no clue why this fails. As a temp workaround, in order to delete users, logged in as admin, visit http://www.criticalcommons.org/acl_users/source_users/manage_users

select the user you want to remove and scroll at the bottom where you will select 'remove users'.

**Comment by Ironman28** [comment]
Perfect!
