### ISSUE TITLE
Password resets are not working for users

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#6]
Currently the only way to reset a password is to contact the admin and have Steve do it manually

**Comment by Ironman28** [comment]
I'm not sure this bug is still a problem. I have had several password resets (by users) work fine recently. Maybe it needs additional testing?

**Comment by mgogoulos** [comment]
I had fixed this one since it has been reported, gmail (that sends the email) was complaining , I have searched for what was the error (through the logs on /var/log/mailog*) and quickly patched it.
