### ISSUE TITLE
Fix tag cloud links 

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#7]
Clicking any link in tag cloud returns 33441+ items! 

E.g. the "economics" tag here:
http://www.criticalcommons.org/cloud_search?portlet=tag-cloud&path=/cc&tags:list=economics&economics:list=Subject

Or "in media res" tag here:
http://www.criticalcommons.org/cloud_search?portlet=tag-cloud&path=/cc&tags:list=in%20media%20res&in%20media%20res:list=Subject

**Comment by ahelme** [comment]
Tested - this is indeed a problem. Added links to description.

**Comment by mgogoulos** [comment]
this is fixed now

**Comment by ahelme** [comment]
Yep, awesome:
http://www.criticalcommons.org/@@search?Subject=technocinema&portal_type=PlumiVideo
