### ISSUE TITLE
Changes to Registration page

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#9]
On page: http://www.criticalcommons.org/register
Is it possible to toggle between Basic and Advanced user requirements? For Advanced, I really need a Home Page URL, Title, Institution and Bio but I don't need this information for Basic users. Can we switch on/off the little red boxes depending on which type of account is being created (or something)?

**Comment by ahelme** [comment]
Mmm, a toggle seems good, but perhaps a future enhancement could be a re-designed registration form... we probably discussed this years ago, but something like:
Basic Registration Form > Success / Email Confirmation of Registration > (on first log-in) Would You Like To Become Advanced User? > Advanced Form > Updated Member Role > Success / Confirmation of Advanced User Status

Anyhow, the selection of Basic or Advanced user could simply toggle the boxes that show up, for now!

**Comment by mgogoulos** [comment]
Now Basic user has hidden these fields, which appear when you select Advanced user. Please test and close the ticket if this is ok

**Comment by mgogoulos** [comment]
i think we are good for now,  shall I close this and reopen in future for further optimization?

**Comment by Ironman28** [comment]
The toggle is brilliant and wonderful! Thank you, Markos. There is just one remaining tweak that needs to happen. Users are very lazy and they put in only the absolute minimum information. For Advanced Users, I need to have little red boxes next to EACH of these items (including Title, Institution, Biography and Home Page) to indicate it is required!

**Comment by ahelme** [comment]
Toggle works great!!

I see Steve, yes all boxes on Advanced User selection must have little red box (required).

**Comment by mgogoulos** [comment]
should be ok now, please try and close this!

**Comment by Ironman28** [comment]
This is great! Closing. But I will open a new ticket for a couple of minor UI text changes on this page.
